import { NextResponse } from "next/server";

// ✅ POST handler for generating course outlines securely on the server
export async function POST(req: Request) {
    try {
        // Parse input from frontend
        const { jsonObject, modality, aiModel } = await req.json();

        // Validate server-side API key (never exposed to client)
        const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "";
        console.log("AI API KEY 28112025 : ", OPENROUTER_API_KEY);
        // Dynamically build course prompt using jsonObject and modality
        const modalityString = [
            modality?.selfPaced && "Self-paced",
            modality?.instructorLed && "Instructor-led",
        ]
            .filter(Boolean)
            .join(", ");

        const keyTask = jsonObject?.tasks?.length > 0 ? jsonObject.tasks[0] : "-";
        const criticalWorkFunction = jsonObject?.criticalWorkFunction || "-";

        const coursePrompt = {
            instruction:
                "You are an expert instructional designer and L&D specialist. Create a structured 10-slide course based on the provided context.",
            input_variables: {
                industry: jsonObject?.industry || "-",
                department: jsonObject?.department || "-",
                job_role: jsonObject?.jobRole || "-",
                critical_work_function: criticalWorkFunction,
                key_task: keyTask,
                modality: modalityString || "-",
            },
            output_format: {
                total_slides: 10,
                bullet_points_per_slide: "3–5 (under 40 words each)",
                style: "Formal, structured, competency-based",
                tone: modalityString.includes("Self-paced")
                    ? "Direct, learner-led tone"
                    : "Facilitator-focused guidance",
            },
        };

        // Prepare request payload for OpenRouter API
        const requestData = {
            model: aiModel || "deepseek/deepseek-chat",
            messages: [
                {
                    role: "system",
                    content:
                        "You are an expert instructional designer and L&D specialist. Return course content strictly in text (no JSON formatting unless requested).",
                },
                {
                    role: "user",
                    content: JSON.stringify(coursePrompt, null, 2),
                },
            ],
            max_tokens: 4000,
            temperature: 0.7,
            top_p: 0.9,
        };

        console.log("🚀 Sending request to OpenRouter with model:", aiModel);

        // Call OpenRouter API
        const response = await fetch(
            "https://openrouter.ai/api/v1/chat/completions",
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${OPENROUTER_API_KEY}`,
                    "Content-Type": "application/json",
                    "HTTP-Referer": process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
                    "X-Title": "AI Course Generator",
                },
                body: JSON.stringify(requestData),
            }
        );

        // Handle errors from OpenRouter
        if (!response.ok) {
            const errorText = await response.text();
            console.error("❌ OpenRouter API Error:", errorText);

            return NextResponse.json(
                {
                    error: `OpenRouter API call failed (${response.status})`,
                    details: errorText,
                },
                { status: response.status }
            );
        }

        // Parse result
        const text = await response.text();
        let result: any;

        try {
            result = JSON.parse(text);
        } catch {
            console.error("⚠️ Could not parse JSON, returning raw text.");
            result = { rawText: text };
        }

        const generatedContent =
            result?.choices?.[0]?.message?.content || result?.rawText;

        if (!generatedContent) {
            return NextResponse.json(
                {
                    error: "No content generated by the AI model.",
                    raw: result,
                },
                { status: 500 }
            );
        }

        return NextResponse.json({
            success: true,
            model: aiModel,
            content: generatedContent,
        });
    } catch (error: any) {
        console.error("⚠️ Server-side course generation error:", error);

        return NextResponse.json(
            {
                error:
                    error.message ||
                    "Internal server error during course generation.",
            },
            { status: 500 }
        );
    }
}
